// The `?` help guide shown over the manual (physical-yarrow) casting flow.
// Pure content — pre-formatted terminal lines handed to the generic
// `<HelpOverlay>` from @hexagram/viewer-core. Headings are BOLD_WHITE, the
// classical 繫辭 (Xici) source is quoted as dim indented blockquotes, body
// text is plain. Long lines wrap to the overlay's inner width at render time.

import { BOLD_WHITE, MUTED_GREY, NORMAL } from '@hexagram/viewer-core'

const heading = (text: string): string => `${BOLD_WHITE}${text}${NORMAL}`
const quote = (text: string): string => `${MUTED_GREY}  │ ${text}${NORMAL}`
const dim = (text: string): string => `${MUTED_GREY}${text}${NORMAL}`

export const MANUAL_GUIDE_TITLE = 'Manual casting · the yarrow-stalk procedure'

export const MANUAL_GUIDE_LINES: string[] = [
  heading('What this is'),
  '',
  'For some three thousand years the Yijing (易經) has been consulted by',
  'sorting a bundle of dried yarrow stalks (蓍草) by hand. This mode lets you',
  'perform that rite yourself: you do the dividing and counting on the table',
  'before you, and the program quietly records each division, derives the',
  'lines, and saves the reading.',
  '',
  'You begin with fifty stalks. One is drawn out at the very start and set',
  'aside — never again touched — leaving forty-nine stalks in play.',
  '',
  quote('大衍之數五十，其用四十有九。'),
  dim('  The number of the Great Expansion is fifty; of these, forty-nine'),
  dim('  are used.'),
  '',
  heading('The four operations (四營)'),
  '',
  'A single round — the classical four operations, or sì yíng (四營) — works',
  'the forty-nine stalks (and, in later rounds, what remains of them) through',
  'four movements. You need only transcribe what each movement leaves in',
  'your hands.',
  '',
  '  1. Divide (分二). Part the stalks into two heaps at random — one to the',
  '     left hand, one to the right.',
  '',
  quote('分而為二以象兩。'),
  dim('  Divide them into two, to represent the two powers, Heaven and Earth.'),
  '',
  '  2. Suspend one (掛一). Take a single stalk from the right heap and hold',
  '     it apart between two fingers. It is counted at the end, but it is',
  '     never sorted.',
  '',
  quote('掛一以象參。'),
  dim('  Suspend one, to represent the third power — humankind, who stands'),
  dim('  between Heaven and Earth.'),
  '',
  '  3. Count by fours (揲四). Set each heap aside in bundles of four until',
  '     fewer than four stalks remain. Those last few stalks are that',
  '     heap’s remainder.',
  '',
  quote('揲之以四以象四時。'),
  dim('  Count them out by fours, to represent the four seasons.'),
  '',
  '  4. Gather the odd stalks (歸奇). Collect the two remainders together',
  '     with the one suspended stalk and lay them aside. Whatever is left',
  '     returns to the bundle for the next round.',
  '',
  quote('歸奇於扐以象閏。'),
  dim('  Return the odd stalks to the fold, to represent the leap month that'),
  dim('  reconciles the calendar.'),
  '',
  heading('What you tell the program each round'),
  '',
  'Once the two heaps are sorted, the prompt asks you for four numbers. Press',
  'Tab to move forward through the fields, Shift+Tab to move back, and Enter',
  'to confirm once the figures are sound.',
  '',
  '  • The left heap’s bundles of four — how many complete groups of four',
  '    stalks it yielded.',
  '  • The left heap’s remainder — the stalks left over once those groups',
  '    are set aside (always one, two, three, or four).',
  '  • The right heap’s bundles of four — the same count for the right heap.',
  '  • The right heap’s remainder — the right heap’s leftover, likewise one',
  '    to four.',
  '',
  heading('Why a remainder is never zero'),
  '',
  'A heap that divides evenly into fours does not leave nothing behind — it',
  'leaves a final group of four. In this counting the remainder is therefore',
  'always one, two, three, or four, and the prompt will gently refuse a zero.',
  '',
  heading('The count must always balance'),
  '',
  'Not a single stalk is ever lost. The program adds together —',
  '',
  '    four times the left heap’s bundles, plus the left heap’s remainder,',
  '    plus four times the right heap’s bundles, plus the right heap’s',
  '    remainder, and finally the one suspended stalk',
  '',
  '— and confirms that the total equals the number of stalks you began the',
  'round with. The strip along the bottom shows how many stalks are so far',
  'accounted for, and turns green the moment the figures balance.',
  '',
  heading('A second check, drawn from the rite itself'),
  '',
  'The one suspended stalk and the two remainders, added together, may fall',
  'only on certain numbers. On the first of a line’s three changes their sum',
  'is either five or nine; on the second and third changes it is either four',
  'or eight. Any other total means a full group of four was mistaken for a',
  'remainder — return it to the bundles and count once more.',
  '',
  heading('Three changes make a line; six lines make a hexagram'),
  '',
  'Three rounds — sān biàn (三變) — settle a single line, and the lines are',
  'built from the bottom upward until six in all have formed. With each round',
  'the pile grows smaller as the set-aside stalks are removed.',
  '',
  quote('四營而成易，十有八變而成卦。'),
  dim('  Four operations complete one change; eighteen changes complete a'),
  dim('  hexagram.'),
  '',
  'Each line settles into one of four values:',
  '',
  '  • 7 — young yang (少陽): a solid line, at rest.',
  '  • 8 — young yin (少陰): a broken line, at rest.',
  '  • 9 — old yang (老陽): a solid line in motion, which turns into yin.',
  '  • 6 — old yin (老陰): a broken line in motion, which turns into yang.',
  '',
  'The lines in motion — the sixes and the nines — change into their',
  'opposites, revealing a second, emerging hexagram beside the first.',
  '',
  heading('Keys'),
  '',
  '  Tab / Shift+Tab   move between the four fields',
  '  Enter             confirm the round (press it again during the pause',
  '                    to move straight on)',
  '  Ctrl+R            undo the current or just-finished line',
  '  ? or Esc          close this guide',
  '',
  dim('Take your time. The count before you on the table is the oracle; the'),
  dim('clock is not.'),
]
