import type { CastingRecord, Hexagram } from '@hexagram/types'
import { describe, expect, it } from 'vitest'

import {
  flowReducer,
  initialFlowState,
  type FlowState,
} from '../src/viewer-flow'

// The flow reducer is PURE — no React, no Ink, no crypto. These tests
// construct a `FlowState` and dispatch actions directly. The random
// `querySubmit` carries the casting plan generated by the imperative shell;
// the reducer only stores it. The interactive path must stay byte-identical.

const STUB_HEXAGRAM: Hexagram = [7, 8, 7, 8, 7, 8]
const STUB_CASTING: CastingRecord = Array.from({ length: 6 }, () => [
  { pick: 24, max: 48 },
  { pick: 20, max: 43 },
  { pick: 16, max: 35 },
]) as CastingRecord
const STUB_PLAN = { hexagram: STUB_HEXAGRAM, casting: STUB_CASTING }

describe('flowReducer — querySubmit', () => {
  it('interactive querySubmit enters casting mode and stores no plan', () => {
    const state: FlowState = {
      ...initialFlowState('interactive', null, null),
      queryBuffer: 'Should I take the journey?',
    }
    const next = flowReducer(state, { type: 'querySubmit' })
    expect(next.mode).toBe('casting')
    expect(next.query).toBe('Should I take the journey?')
    expect(next.castingPlan).toBeNull()
  })

  it('random querySubmit with a plan enters casting mode and stores the plan', () => {
    const state: FlowState = {
      ...initialFlowState('random', null, null),
      queryBuffer: 'Will the harvest be plentiful?',
    }
    const next = flowReducer(state, { type: 'querySubmit', plan: STUB_PLAN })
    // The random flow no longer short-cuts to computing — it plays back
    // cast-by-cast through `casting`, the SAME mode the interactive flow uses.
    expect(next.mode).toBe('casting')
    expect(next.query).toBe('Will the harvest be plentiful?')
    expect(next.castingPlan).toBe(STUB_PLAN)
  })

  it('querySubmit on an empty query buffer is a no-op', () => {
    const state = initialFlowState('random', null, null)
    const next = flowReducer(state, { type: 'querySubmit', plan: STUB_PLAN })
    expect(next).toBe(state)
  })

  it('querySubmit on a whitespace-only query buffer is a no-op', () => {
    const state: FlowState = {
      ...initialFlowState('interactive', null, null),
      queryBuffer: '   ',
    }
    const next = flowReducer(state, { type: 'querySubmit' })
    expect(next).toBe(state)
  })

  it('keeps the reducer pure — the input state is not mutated', () => {
    const state: FlowState = {
      ...initialFlowState('random', null, null),
      queryBuffer: 'A query',
    }
    const snapshot = { ...state }
    flowReducer(state, { type: 'querySubmit', plan: STUB_PLAN })
    expect(state).toEqual(snapshot)
    expect(state.mode).toBe('awaitingQuery')
    expect(state.castingPlan).toBeNull()
  })
})

describe('initialFlowState', () => {
  it('starts castingPlan as null', () => {
    expect(initialFlowState('interactive', null, null).castingPlan).toBeNull()
    expect(initialFlowState('random', null, null).castingPlan).toBeNull()
  })
})

describe('flowReducer — splitCommitted advance path', () => {
  it('advances the slot pointer cast-by-cast and records each split', () => {
    let state: FlowState = {
      ...initialFlowState('random', null, null),
      mode: 'casting',
      castingPlan: STUB_PLAN,
    }
    state = flowReducer(state, { type: 'splitCommitted', pick: 24, max: 48 })
    expect(state.castIndex).toBe(1)
    expect(state.lineIndex).toBe(0)
    expect(state.partialCasting[0][0]).toEqual({ pick: 24, max: 48 })

    state = flowReducer(state, { type: 'splitCommitted', pick: 20, max: 43 })
    expect(state.castIndex).toBe(2)

    // Third cast of the line carries the resolved Line and advances to line 2.
    state = flowReducer(state, {
      type: 'splitCommitted',
      pick: 16,
      max: 35,
      line: 7,
    })
    expect(state.lineIndex).toBe(1)
    expect(state.castIndex).toBe(0)
    expect(state.completedLines).toEqual([7])
  })

  it('enters computing after the eighteenth cast', () => {
    let state: FlowState = {
      ...initialFlowState('random', null, null),
      mode: 'casting',
      castingPlan: STUB_PLAN,
    }
    for (let cast = 0; cast < 18; cast += 1) {
      const isThird = cast % 3 === 2
      state = flowReducer(state, {
        type: 'splitCommitted',
        pick: 24,
        max: 48,
        ...(isThird ? { line: 7 as const } : {}),
      })
    }
    expect(state.mode).toBe('computing')
    expect(state.completedLines).toHaveLength(6)
    // The casting plan is cleared on the `computing` transition — it has
    // served its purpose (all 18 casts played back into `partialCasting`).
    expect(state.castingPlan).toBeNull()
  })
})
