import process from 'node:process'

import { generateRandomConsultation } from '@hexagram/core/random'

import { logAndSaveConsultationOutput } from './cli-output-file'
import { getUserQuery } from './cli-prompts'
import { resolveOutputMode, resolveWrapWidth } from './cli-utils-mode'
import { runConsultationViewer } from './cli-viewer'

export * from '@hexagram/core/random'

export async function main(): Promise<void> {
  try {
    if (resolveOutputMode() === 'plain') {
      // Plain mode keeps the terminal-side Inquirer prompt for the query;
      // the casting is generated by the RNG and the reading is printed +
      // saved directly.
      const query = await getUserQuery()
      const { hexagram, casting } = generateRandomConsultation()
      await logAndSaveConsultationOutput(query, hexagram, casting)
    } else {
      // Ink mode opens straight into the viewer with an editable query box;
      // the casting is generated inside the viewer's compute effect once
      // the query is submitted.
      await runConsultationViewer({
        flowKind: 'random',
        maxWrapWidth: resolveWrapWidth(),
      })
    }

    process.exit(0)
  } catch (error) {
    console.error(error)
    process.exit(1)
  }
}
