import { randomInt } from 'node:crypto'
import process from 'node:process'

import { makeLineGenerator, stalksBeforeParting } from '.'
import { resolveOutputMode, resolveWrapWidth } from './cli-utils-mode'
import { logAndSaveConsultationOutput } from './cli-output-file'
import { getUserQuery } from './cli-prompts'
import { runConsultationViewer } from './cli-viewer'
import {
  assertIsCastingRecord,
  assertIsFourOperationsResult,
  assertIsHexagram,
  assertIsLine,
  assertIsLineGeneratorResult,
  type CastingRecord,
  type Hexagram,
  type Line,
  type LineGeneratorResult,
} from './types'

// REF: https://nodejs.org/api/crypto.html#crypto_crypto_randomint_min_max_callback
export const splitStalksRandomly = (unpartedStalks: number[]): number =>
  randomInt(1, unpartedStalks.length - 1)

export const getOneRandomLine = function* (): Generator<
  /* Yield */ LineGeneratorResult,
  /* Return */ void,
  /* Next */ void
> {
  // `max` mirrors the selectable range an interactive prompt would show for
  // this round ("Pick a number from 1 to max"), so RNG castings replay the
  // same way as interactive ones.
  const firstMax = stalksBeforeParting.length - 1
  const firstSplit = splitStalksRandomly(stalksBeforeParting)
  const roundOneArguments = {
    unpartedStalks: stalksBeforeParting,
    suspendedFromNextRound: [],
    partStalksAtIndex: firstSplit,
  }
  const lineGenerator = makeLineGenerator(roundOneArguments)
  const roundOneResults = lineGenerator.next().value
  // console.log('roundOneResults', roundOneResults)

  assertIsFourOperationsResult(roundOneResults)

  const secondMax = roundOneResults.unpartedStalks.length - 1
  const secondSplit = splitStalksRandomly(roundOneResults.unpartedStalks)
  const roundTwoResults = lineGenerator.next(secondSplit).value
  // console.log('roundTwoResults', roundTwoResults)

  assertIsFourOperationsResult(roundTwoResults)

  const thirdMax = roundTwoResults.unpartedStalks.length - 1
  const thirdSplit = splitStalksRandomly(roundTwoResults.unpartedStalks)
  const roundThreeResults = lineGenerator.next(thirdSplit).value
  // console.log('roundThreeResults', roundThreeResults)

  assertIsFourOperationsResult(roundThreeResults)

  const { value: line } = lineGenerator.next()
  // console.log('line', line)

  assertIsLine(line)

  yield {
    line,
    rounds: [roundOneResults, roundTwoResults, roundThreeResults] as const,
    splits: [
      { pick: firstSplit, max: firstMax },
      { pick: secondSplit, max: secondMax },
      { pick: thirdSplit, max: thirdMax },
    ],
  }
}

// 十有八變而成卦。
export const makeRandomHexagramGenerator = function* (): Generator<
  /* Yield */ LineGeneratorResult,
  /* Return */ void,
  /* Next */ void
> {
  const lines = Array.from({ length: 6 }, () => getOneRandomLine)

  for (const line of lines) {
    yield* line()
  }
}
export const generateRandomHexagram = (): Hexagram => {
  const getHexagram = makeRandomHexagramGenerator()

  const hexagram = Array.from({ length: 6 }, () => getHexagram.next()).map(
    ({ value }) => {
      assertIsLineGeneratorResult(value)

      return value.line
    },
  )

  assertIsHexagram(hexagram)

  return hexagram
}

// Like `generateRandomHexagram`, but also returns the eighteen RNG-chosen
// stalk divisions (the casting record) so the CLI can show how the hexagram
// was cast. `generateRandomHexagram` is kept untouched as the library API.
export const generateRandomConsultation = (): {
  hexagram: Hexagram
  casting: CastingRecord
} => {
  const getHexagram = makeRandomHexagramGenerator()

  const results = Array.from({ length: 6 }, () => getHexagram.next()).map(
    ({ value }) => {
      assertIsLineGeneratorResult(value)

      return value
    },
  )

  const hexagram = results.map((result) => result.line)
  assertIsHexagram(hexagram)

  const casting = results.map((result) => result.splits)
  assertIsCastingRecord(casting)

  return { hexagram, casting }
}

export const generateRandomHexagrams = (
  hexagramCount = 1_000,
): [Line, Line, Line, Line, Line, Line][] =>
  Array.from({ length: hexagramCount }, () => generateRandomHexagram()).map(
    () => generateRandomHexagram(),
  )

const roundToPrecision = (number: number, precision = 4) =>
  number.toPrecision(precision)

export const generateRandomLines = (
  lineCount = 1_000,
): Record<string, string> => {
  const runs = Array.from({ length: lineCount }, () => getOneRandomLine).map(
    (getOneLine) => getOneLine().next(),
  )

  const breakdown = Object.fromEntries(
    [5, 6, 7, 8, 9, 10].map((value) => {
      const count = runs.filter((result) => result.value?.line === value).length

      return [
        `Line ${value}`,
        `${roundToPrecision((count / lineCount) * 100)}%`,
      ]
    }),
  )

  return breakdown
}

export async function main(): Promise<void> {
  try {
    if (resolveOutputMode() === 'plain') {
      // Plain mode keeps the terminal-side Inquirer prompt for the query;
      // the casting is generated by the RNG and the reading is printed +
      // saved directly.
      const query = await getUserQuery()
      const { hexagram, casting } = generateRandomConsultation()
      await logAndSaveConsultationOutput(query, hexagram, casting)
    } else {
      // Ink mode opens straight into the viewer with an editable query box;
      // the casting is generated inside the viewer's compute effect once
      // the query is submitted.
      await runConsultationViewer({
        flowKind: 'random',
        maxWrapWidth: resolveWrapWidth(),
      })
    }

    process.exit(0)
  } catch (error) {
    console.error(error)
    process.exit(1)
  }
}
