import { initialLineState, maxPickFor, performCast } from '@hexagram/core'
import type {
  AdvanceableLineState,
  CastingRecord,
  Hexagram,
  LineState,
} from '@hexagram/core/types'
import { describe, expect, it } from 'vitest'

import {
  flowReducer,
  initialFlowState,
  recordedMaxFor,
  type CastingPlan,
  type FlowKind,
  type FlowState,
} from '../src/viewer-flow'

it('FlowKind admits "manual"', () => {
  const kind: FlowKind = 'manual'
  expect(kind).toBe('manual')
})

// The flow reducer is PURE — no React, no Ink, no crypto. These tests
// construct a `FlowState` and dispatch actions directly. The random
// `querySubmit` carries the casting plan generated by the imperative shell;
// the reducer only stores it. The interactive path must stay byte-identical.

// A casting plan whose recorded `max`es and resolved `Line`s are EXACTLY what
// `performCast` produces for the given picks. The reducer now DERIVES both
// itself (it no longer trusts an action payload), so the fixture must be
// internally consistent — the old hard-coded STUB arrays fabricated a
// max/line and would no longer survive cast-by-cast replay.
function realPlan(picksByLine: readonly (readonly number[])[]): CastingPlan {
  const casting = picksByLine.map((linePicks) => {
    let s: LineState = initialLineState
    return linePicks.map((pick) => {
      const max = maxPickFor(s as AdvanceableLineState)
      s = performCast(s as AdvanceableLineState, pick)
      return { pick, max }
    })
  }) as CastingRecord
  const hexagram = picksByLine.map((linePicks) => {
    let s: LineState = initialLineState
    for (const pick of linePicks) {
      s = performCast(s as AdvanceableLineState, pick)
    }
    return (s as Extract<LineState, { phase: '3rd-cast' }>).line
  }) as Hexagram
  return { hexagram, casting }
}

// pick = 1 is always ≤ selectablePickMax(recordedMax) for any running stalk
// count, so every one of the eighteen casts is legal regardless of the line.
const PLAN: CastingPlan = realPlan(Array.from({ length: 6 }, () => [1, 1, 1]))

describe('flowReducer — querySubmit', () => {
  it('interactive querySubmit enters casting mode and stores no plan', () => {
    const state: FlowState = {
      ...initialFlowState('interactive', null, null),
      queryBuffer: 'Should I take the journey?',
    }
    const next = flowReducer(state, { type: 'querySubmit' })
    expect(next.mode).toBe('casting')
    expect(next.query).toBe('Should I take the journey?')
    expect(next.castingPlan).toBeNull()
  })

  it('random querySubmit with a plan enters casting mode and stores the plan', () => {
    const state: FlowState = {
      ...initialFlowState('random', null, null),
      queryBuffer: 'Will the harvest be plentiful?',
    }
    const next = flowReducer(state, { type: 'querySubmit', plan: PLAN })
    // The random flow no longer short-cuts to computing — it plays back
    // cast-by-cast through `casting`, the SAME mode the interactive flow uses.
    expect(next.mode).toBe('casting')
    expect(next.query).toBe('Will the harvest be plentiful?')
    expect(next.castingPlan).toBe(PLAN)
  })

  it('querySubmit on an empty query buffer is a no-op', () => {
    const state = initialFlowState('random', null, null)
    const next = flowReducer(state, { type: 'querySubmit', plan: PLAN })
    expect(next).toBe(state)
  })

  it('querySubmit on a whitespace-only query buffer is a no-op', () => {
    const state: FlowState = {
      ...initialFlowState('interactive', null, null),
      queryBuffer: '   ',
    }
    const next = flowReducer(state, { type: 'querySubmit' })
    expect(next).toBe(state)
  })

  it('keeps the reducer pure — the input state is not mutated', () => {
    const state: FlowState = {
      ...initialFlowState('random', null, null),
      queryBuffer: 'A query',
    }
    const snapshot = { ...state }
    flowReducer(state, { type: 'querySubmit', plan: PLAN })
    expect(state).toEqual(snapshot)
    expect(state.mode).toBe('awaitingQuery')
    expect(state.castingPlan).toBeNull()
  })
})

describe('initialFlowState', () => {
  it('starts castingPlan as null', () => {
    expect(initialFlowState('interactive', null, null).castingPlan).toBeNull()
    expect(initialFlowState('random', null, null).castingPlan).toBeNull()
  })

  it('starts lineState at the initial 0th-cast phase', () => {
    expect(initialFlowState('interactive', null, null).lineState).toBe(
      initialLineState,
    )
  })
})

describe('flowReducer — splitCommitted advance path', () => {
  it('advances the slot and DERIVES each split (max + resolved line) itself', () => {
    let state: FlowState = {
      ...initialFlowState('random', null, null),
      mode: 'casting',
      castingPlan: PLAN,
    }
    // Cast 1 — the action carries only the pick; the reducer derives max = 48.
    state = flowReducer(state, {
      type: 'splitCommitted',
      pick: PLAN.casting[0][0]!.pick,
    })
    expect(state.castIndex).toBe(1)
    expect(state.lineIndex).toBe(0)
    expect(state.partialCasting[0][0]).toEqual(PLAN.casting[0][0])

    // Cast 2
    state = flowReducer(state, {
      type: 'splitCommitted',
      pick: PLAN.casting[0][1]!.pick,
    })
    expect(state.castIndex).toBe(2)
    expect(state.partialCasting[0][1]).toEqual(PLAN.casting[0][1])

    // Cast 3 — reducer resolves the line via performCast and advances to line 2.
    state = flowReducer(state, {
      type: 'splitCommitted',
      pick: PLAN.casting[0][2]!.pick,
    })
    expect(state.lineIndex).toBe(1)
    expect(state.castIndex).toBe(0)
    expect(state.completedLines).toEqual([PLAN.hexagram[0]])
  })

  it('enters computing after the eighteenth cast and clears the plan', () => {
    let state: FlowState = {
      ...initialFlowState('random', null, null),
      mode: 'casting',
      castingPlan: PLAN,
    }
    for (let lineIndex = 0; lineIndex < 6; lineIndex += 1) {
      for (let castIndex = 0; castIndex < 3; castIndex += 1) {
        state = flowReducer(state, {
          type: 'splitCommitted',
          pick: PLAN.casting[lineIndex]![castIndex]!.pick,
        })
      }
    }
    expect(state.mode).toBe('computing')
    expect(state.completedLines).toEqual([...PLAN.hexagram])
    // S5 preserved: the plan is cleared on the `computing` transition — it has
    // served its purpose (all 18 casts played back into `partialCasting`).
    expect(state.castingPlan).toBeNull()
  })
})

describe('flowReducer — playbackSkipped', () => {
  it('fills the partial casting record and lines from the plan, enters computing', () => {
    const state: FlowState = {
      ...initialFlowState('random', null, null),
      mode: 'casting',
      castingPlan: PLAN,
    }
    const next = flowReducer(state, { type: 'playbackSkipped' })
    expect(next.mode).toBe('computing')
    // The partial casting record is filled wholesale from the plan's casting.
    expect(next.partialCasting).toEqual(PLAN.casting)
    // ...but as a fresh array, not an alias of the plan's `casting`. Every
    // other transition in the reducer builds new arrays; sharing the plan's
    // reference would break that convention and risk latent corruption.
    expect(next.partialCasting).not.toBe(state.castingPlan!.casting)
    // The completed lines are filled from the plan's hexagram.
    expect(next.completedLines).toEqual([...PLAN.hexagram])
    // ...likewise a fresh array, not an alias of the plan's `hexagram`.
    expect(next.completedLines).not.toBe(state.castingPlan!.hexagram)
    // The plan is cleared, consistent with the last-cast splitCommitted.
    expect(next.castingPlan).toBeNull()
  })

  it('produces a state byte-identical to eighteen splitCommitteds', () => {
    const base: FlowState = {
      ...initialFlowState('random', null, null),
      mode: 'casting',
      castingPlan: PLAN,
    }
    // Play the plan through cast-by-cast, exactly as the full animation would.
    let played: FlowState = base
    for (let lineIndex = 0; lineIndex < 6; lineIndex += 1) {
      for (let castIndex = 0; castIndex < 3; castIndex += 1) {
        played = flowReducer(played, {
          type: 'splitCommitted',
          pick: PLAN.casting[lineIndex]![castIndex]!.pick,
        })
      }
    }
    const skipped = flowReducer(base, { type: 'playbackSkipped' })
    // The saved Consultation is built from partialCasting + completedLines —
    // those must match what the full eighteen-cast playback produced.
    expect(skipped.mode).toBe(played.mode)
    expect(skipped.partialCasting).toEqual(played.partialCasting)
    expect(skipped.completedLines).toEqual(played.completedLines)
    expect(skipped.castingPlan).toBe(played.castingPlan)
  })

  it('is a no-op when castingPlan is null', () => {
    const state: FlowState = {
      ...initialFlowState('interactive', null, null),
      mode: 'casting',
    }
    const next = flowReducer(state, { type: 'playbackSkipped' })
    expect(next).toBe(state)
  })

  it('is a no-op when mode is not casting', () => {
    const state: FlowState = {
      ...initialFlowState('random', null, null),
      mode: 'awaitingQuery',
      castingPlan: PLAN,
    }
    const next = flowReducer(state, { type: 'playbackSkipped' })
    expect(next).toBe(state)
  })

  it('keeps the reducer pure — the input state is not mutated', () => {
    const state: FlowState = {
      ...initialFlowState('random', null, null),
      mode: 'casting',
      castingPlan: PLAN,
    }
    const snapshot = structuredClone(state)
    flowReducer(state, { type: 'playbackSkipped' })
    expect(state).toEqual(snapshot)
    expect(state.mode).toBe('casting')
    expect(state.castingPlan).toBe(PLAN)
  })
})

describe('flowReducer — lineRewound', () => {
  const inCastingMode = (overrides: Partial<FlowState> = {}): FlowState => ({
    ...initialFlowState('manual', null, null),
    mode: 'casting',
    query: 'Will the rains come?',
    ...overrides,
  })

  it("clears the current line's casts on a mid-line rewind", () => {
    const state = inCastingMode({
      lineIndex: 2,
      castIndex: 2,
      partialCasting: [
        [
          { pick: 21, max: 48 },
          { pick: 17, max: 43 },
          { pick: 9, max: 39 },
        ],
        [
          { pick: 22, max: 48 },
          { pick: 12, max: 40 },
          { pick: 8, max: 36 },
        ],
        [{ pick: 19, max: 48 }, { pick: 14, max: 42 }, null],
        [null, null, null],
        [null, null, null],
        [null, null, null],
      ],
      completedLines: [7, 8],
      castingBuffer: 'leftover',
      error: 'stale error',
    })
    const next = flowReducer(state, { type: 'lineRewound' })
    expect(next.lineIndex).toBe(2)
    expect(next.castIndex).toBe(0)
    expect(next.partialCasting[2]).toEqual([null, null, null])
    // Earlier completed lines stay intact — only the current (in-progress) one cleared.
    expect(next.partialCasting[0]).toEqual(state.partialCasting[0])
    expect(next.partialCasting[1]).toEqual(state.partialCasting[1])
    expect(next.completedLines).toEqual([7, 8])
    expect(next.castingBuffer).toBe('')
    expect(next.error).toBeNull()
  })

  it('rewinds to the previous line when called immediately after a line completes', () => {
    const state = inCastingMode({
      lineIndex: 2,
      castIndex: 0,
      partialCasting: [
        [
          { pick: 21, max: 48 },
          { pick: 17, max: 43 },
          { pick: 9, max: 39 },
        ],
        [
          { pick: 22, max: 48 },
          { pick: 12, max: 40 },
          { pick: 8, max: 36 },
        ],
        [null, null, null],
        [null, null, null],
        [null, null, null],
        [null, null, null],
      ],
      completedLines: [7, 8],
    })
    const next = flowReducer(state, { type: 'lineRewound' })
    expect(next.lineIndex).toBe(1)
    expect(next.castIndex).toBe(0)
    expect(next.partialCasting[1]).toEqual([null, null, null])
    expect(next.partialCasting[0]).toEqual(state.partialCasting[0])
    expect(next.completedLines).toEqual([7])
  })

  it('is a no-op at line 0 cast 0', () => {
    const state = inCastingMode()
    const next = flowReducer(state, { type: 'lineRewound' })
    expect(next).toBe(state)
  })

  it('is a no-op when flowKind !== manual', () => {
    const state = inCastingMode({ flowKind: 'interactive', castIndex: 2 })
    const next = flowReducer(state, { type: 'lineRewound' })
    expect(next).toBe(state)
  })

  it('is a no-op when mode !== casting', () => {
    const state: FlowState = {
      ...inCastingMode({ castIndex: 2 }),
      mode: 'done',
    }
    const next = flowReducer(state, { type: 'lineRewound' })
    expect(next).toBe(state)
  })
})

// The per-line algorithm now lives in the reducer (`FlowState.lineState`,
// advanced by the pure `performCast`). These tests fold in what the deleted
// `useLineGenerator` hook used to cover: that a rewind resets the algorithm in
// ONE pure dispatch — no ref-before-dispatch ordering handshake (the old S4
// seam). They drive the manual flow, the only one that rewinds.
describe('flowReducer — lineRewound resets the per-line algorithm', () => {
  const manualCasting = (): FlowState => ({
    ...initialFlowState('manual', null, null),
    mode: 'casting',
    query: 'Will the rains come?',
  })

  it('mid-line rewind clears the line and resets the selectable max to 48', () => {
    let state = manualCasting()
    // First cast advances the line: the round-2 selectable max drops below 48.
    state = flowReducer(state, { type: 'splitCommitted', pick: 20 })
    expect(recordedMaxFor(state.lineState)).toBeLessThan(48)

    // One pure dispatch resets BOTH the slot pointer and the lineState.
    state = flowReducer(state, { type: 'lineRewound' })
    expect(recordedMaxFor(state.lineState)).toBe(48)
    expect(state.lineIndex).toBe(0)
    expect(state.castIndex).toBe(0)
    expect(state.partialCasting[0]).toEqual([null, null, null])
  })

  it('after rewind, a fresh first cast rebuilds the same round-2 max', () => {
    let state = manualCasting()
    state = flowReducer(state, { type: 'splitCommitted', pick: 20 })
    const round2Max = recordedMaxFor(state.lineState)
    state = flowReducer(state, { type: 'lineRewound' })
    state = flowReducer(state, { type: 'splitCommitted', pick: 20 })
    expect(recordedMaxFor(state.lineState)).toBe(round2Max)
  })
})

// Seam 8: `lineRewound` (manual-only) never null-checks `castingPlan` — it
// relies on the invariant that a manual flow never carries a plan. Pin that
// invariant at the entry point so the rewind path's safety is guarded.
describe('manual flow carries no casting plan', () => {
  it('manual querySubmit enters casting with a null plan', () => {
    const s = initialFlowState('manual', null, null)
    const withQuery = flowReducer(s, {
      type: 'queryChange',
      value: 'a question',
    })
    const after = flowReducer(withQuery, { type: 'querySubmit' })
    expect(after.mode).toBe('casting')
    expect(after.castingPlan).toBeNull()
  })
})
