#!/usr/bin/env node

import process from 'node:process'

import {
  getUserQuery,
  logAndSaveConsultationOutput,
  resolveCastBounceMs,
  resolveOutputMode,
  resolveSliderSweepMs,
  resolveWrapWidth,
  runConsultationViewer,
} from '@hexagram/casting-ui'
import { generateRandomConsultation } from '@hexagram/core/random'

async function main(): Promise<void> {
  try {
    if (resolveOutputMode() === 'plain') {
      // Plain mode keeps the terminal-side Inquirer prompt for the query;
      // the casting is generated by the RNG and the reading is printed +
      // saved directly.
      const query = await getUserQuery()
      const { hexagram, casting } = generateRandomConsultation()
      await logAndSaveConsultationOutput(query, hexagram, casting)
    } else {
      // Ink mode opens straight into the viewer with an editable query box;
      // the casting is generated in the viewer's Query-submit handler when
      // the query is submitted (the compute effect only saves the file).
      await runConsultationViewer({
        flowKind: 'random',
        maxWrapWidth: resolveWrapWidth(),
        sliderSweepMs: resolveSliderSweepMs(),
        castBounceMs: resolveCastBounceMs(),
      })
    }

    process.exit(0)
  } catch (error) {
    console.error(error)
    process.exit(1)
  }
}

await main()
