#!/usr/bin/env node

import process from 'node:process'

import {
  getUserQuery,
  logAndSaveConsultationOutput,
  resolveOutputMode,
  resolveRandomViewerArgs,
  runConsultationViewer,
} from '@hexagram/casting-ui'
import { generateRandomConsultation } from '@hexagram/core/random-casting'

import { anchorCwdToWorkspaceRoot } from './workspace-root.js'

async function main(): Promise<void> {
  try {
    // Anchor cwd to the monorepo root so the save (plain and Ink alike resolve
    // `<cwd>/consultations` via `defaultConsultationsDir`) lands on
    // `<repo-root>/consultations` regardless of the invocation directory.
    anchorCwdToWorkspaceRoot()
    if (resolveOutputMode() === 'plain') {
      // Plain mode keeps the terminal-side Inquirer prompt for the query;
      // the casting is generated by the RNG and the reading is printed +
      // saved directly.
      const query = await getUserQuery()
      const { hexagram, casting } = generateRandomConsultation()
      await logAndSaveConsultationOutput(query, hexagram, casting)
    } else {
      // Ink mode opens straight into the viewer with an editable query box;
      // the casting is generated in the viewer's Query-submit handler when
      // the query is submitted (the compute effect only saves the file).
      // `resolveRandomViewerArgs()` derives every flag — including
      // `inputMode`, so `--numeric-input` reaches the number-mode reveal.
      await runConsultationViewer(resolveRandomViewerArgs())
    }

    process.exit(0)
  } catch (error) {
    console.error(error)
    process.exit(1)
  }
}

await main()
