#!/usr/bin/env node

import process from 'node:process'

import {
  getUserQuery,
  isUserExitPromptError,
  logAndSaveConsultationOutput,
  resolveOutputMode,
  resolveRandomViewerArgs,
  runConsultationViewer,
} from '@hexagram/casting-ui'
import { generateRandomConsultation } from '@hexagram/core/random-casting'

import { workspaceConsultationsDir } from './workspace-root.js'

async function main(): Promise<void> {
  try {
    // Resolve the repo-root-anchored consultations dir and thread it explicitly
    // to the save edge (no cwd mutation — FCIS). Both the plain save and the
    // Ink viewer receive it as `consultationsDir`, so the reading lands on
    // `<repo-root>/consultations` regardless of the invocation directory.
    const consultationsDir = workspaceConsultationsDir()
    if (resolveOutputMode() === 'plain') {
      // Plain mode keeps the terminal-side Inquirer prompt for the query;
      // the casting is generated by the RNG and the reading is printed +
      // saved directly.
      const query = await getUserQuery()
      const { hexagram, casting } = generateRandomConsultation()
      await logAndSaveConsultationOutput(
        query,
        hexagram,
        casting,
        consultationsDir,
      )
    } else {
      // Ink mode opens straight into the viewer with an editable query box;
      // the casting is generated in the viewer's Query-submit handler when
      // the query is submitted (the compute effect only saves the file).
      // `resolveRandomViewerArgs()` derives every flag — including
      // `inputMode`, so `--numeric-input` reaches the number-mode reveal.
      await runConsultationViewer({
        ...resolveRandomViewerArgs(),
        consultationsDir,
      })
    }

    process.exit(0)
  } catch (error) {
    // Ctrl+C at the plain-mode Inquirer query prompt is a clean user quit, not
    // a failure — match `interactive.ts` and exit 0 instead of 1.
    if (isUserExitPromptError(error)) process.exit(0)

    console.error(error)
    process.exit(1)
  }
}

await main()
