name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set node 24
        uses: actions/setup-node@v6
        with:
          node-version: '>=24.6.0'
          cache: pnpm

      - name: Install
        run: pnpm install --ignore-scripts

      - name: Lint
        run: pnpm run lint:check

      - name: Boundaries
        run: pnpm run boundaries:check

      - name: Typecheck
        run: pnpm run type:check

      - name: Format check
        run: pnpm run format:check

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ['>=24.6.0']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test
